dist: xenial
sudo: required

language: scala

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier

before_install:
- docker run -d -p 9200:9200 -p 9300:9300 -e "path.repo=/tmp" -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

scala:
- 2.12.10
- 2.13.1

script:
- sbt clean scalafmtCheck scalafmtSbtCheck test

jdk:
- openjdk8
- openjdk11
